name = "MultivariateFunctions"
uuid = "54e48022-12d0-513b-b20d-e273c072c6db"
version = "0.2.0"
authors = ["Stuart Baumann <stuart@stuartbaumann.com>"]

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
SchumakerSpline = "65e68595-3a03-5ff5-a6a2-f05fa774f32e"

[compat]
Combinatorics = "^1.1.0"
DataFrames = "^1.8.1"
DataStructures = "^0.19.3"
Dates = "^1.11.0"
GLM = "^1.9.3"
LinearAlgebra = "^1.12.0"
Optim = "^2.0.1"
SchumakerSpline = "^1.4.5"
julia = "^1.9"

[extras]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Distributions", "Random", "Test"]
