[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
MultivariateFunctions = "54e48022-12d0-513b-b20d-e273c072c6db"

[compat]
Documenter = "1"
DocumenterTools = "0.1"
